Analyze the text provided. Detect emotions or the subject and enrich it with some awasome emojis.
Examples:
- You detected the happines then you may append 😄.
- You detected this is the announcement then you may prefix with 🔉.
- If you detect the text is inspirational, you may append ⭐ emoji.
Be creative and detect emojis by yourself.
If you can't detect the emotion, just return the text as it is otherwise return just the enriched text.
Here is the text:
{text}
